### PR TITLE
Made the "Join Now" page in accordance to issue#16

### PR DESCRIPTION
**Pull request by PulkitMishra**
@anubhavp28 check if it's okay. Suggest UI changes if any.
Please check : https://pulkitmishra.github.io/iiitkalyanifosc.github.io/join.html for review 
Also, squash and merge please :)

### CODE REVIEW

**Comment by anubhavp28** [comment]
@PulkitMishra 
* There is no need for join page to have that FOSC banner up at the top. 
* You broke the footer div CSS styling, it looked different and IMO better (see at [iiitkalyanifosc.github.io](https://iiitkalyanifosc.github.io)).  
* The page appears broken on mobile, see - 
untitled

* Also why are you using '!important', there is no need of it and that is bad practice also. You copied the code from somewhere 😆 ?

**Comment by PulkitMishra** [comment]
@anubhavp28

1. I think we should keep the banner. It looks good
2. I can reverse it back, if you want.
3. I haven't made changes in mobile-style.css
4. YUS! Bootstrap aal the way xD

**Comment by anubhavp28** [comment]
@PulkitMishra 
* keep the banner
* yeah, sure make it look like it did before
* yeah, fix it for mobile
* 🤔

**Comment by zeus0789** [comment]
@anubhavp28  What is the second tab you have in the picture?

**Comment by PulkitMishra** [comment]
@anubhavp28 minor fixes here and there. Done. Also, can we have a separate issue for the mobile thing?
I'll take that up too.

**Pull request merged**
