### PR TITLE
Add custom 404 page

### PR DESCRIPTION
**Pull request by Satyam-TG**
Added a custom 404 page to display an error in different programming languages' print statements.
Have a look at https://satyam-tg.github.io/fosc_website/someincorrecturl

### CODE REVIEW

**Comment by PulkitMishra** [comment]
Cool.

**Comment by Satyam-TG** [comment]
@PulkitMishra I have a single sentence answer.
Easter eggs are always hidden.

**Comment by anubhavp28** [comment]
@Satyam-TG `changetext()` function should be attached to `DOMContentLoaded` event, and not `onload`.

**Comment by Satyam-TG** [comment]
@anubhavp28 I had also thought of doing it. Will do it in the morning. I will also add print statements from more languages.

**Comment by Satyam-TG** [comment]
@anubhavp28 changetext() now gets executed on DOMContentLoaded event.

**Comment by anubhavp28** [comment]
Can you convert all paths in your _404.html_ and _404.css_, to absolute from relative? See the problem is when your _404.html_ is called from a directory other than root - https://satyam-tg.github.io/fosc_website/nonexistentfolder/missing.html

**Comment by Satyam-TG** [comment]
@anubhavp28 did it.

**Pull request merged**
