### PR TITLE
Responsive Attributes to Navigation bar

### PR DESCRIPTION
**Pull request by zeus0789**
Please Note: Ignore the first4 older commits.
Merge commits :
https://github.com/IIITKalyaniFOSC/iiitkalyanifosc.github.io/commit/1cb92c67da9ea23fe4ac99924ca15189a6f8fc12
and 
https://github.com/IIITKalyaniFOSC/iiitkalyanifosc.github.io/commit/365abb646aa035516791a3e77ec836bd788aafd3

### CODE REVIEW

**Comment by PulkitMishra** [comment]
Hey @zeus0789  can you please attach the link of the website along with your pull request so that people can easily review it.

**Comment by anubhavp28** [comment]
@zeus0789 Would mind hosting your repository on github pages? It is tedious to clone your repository and run it locally.

**Comment by PulkitMishra** [comment]
@zeus0789 open your repo -> go to settings -> scroll down to GitHub pages -> change source from none to master branch -> save -> page will refresh and it will produce a link at the very same spot -> share that link here

**Comment by anubhavp28** [comment]
@zeus0789 Nice work! though the FOSC logo seems off from the middle(vertically). Do we really need to change the colour of navigation bar from white to black? I guess we should stick to a particular colour scheme. Animations? I have no problem with lack of animations by the way.

**Comment by zeus0789** [comment]
@PulkitMishra @anubhavp28 https://zeus0789.github.io/iiitkalyanifosc.github.io/

**Comment by zeus0789** [comment]
@anubhavp28 okay will deal with the color scheme and theme of the nav bar in the next commit?!?

**Comment by zeus0789** [comment]
@anubhavp28 we can do the animations later. This commit is kinda basic stuff

**Pull request closed without merging**
