### PR TITLE
Adds and modifies projects.html

### PR DESCRIPTION
**Pull request by zeus0789**
New look to the page.
Check it out: https://zeus0789.github.io/iiitkalyanifosc.github.io/

### CODE REVIEW

**Comment by zeus0789** [comment]
squash करके merge कर दिया जाए.

**Comment by Omkar-Ajnadkar** [comment]
@zeus0789  Add repo link to the respective project so that it can be easily accessible...

**Comment by zeus0789** [comment]
@Omkar-Ajnadkar Done.

**Comment by PulkitMishra** [comment]
@anubhavp28 looks good. Merge?

**Pull request merged**
