### PR TITLE
add events page

### PR DESCRIPTION
**Pull request by anubhavp28**
This pull request should complete the website.

### CODE REVIEW

**Comment by zeus0789** [comment]
@anubhavp28 Attach link please

**Comment by anubhavp28** [comment]
https://anubhavp28.github.io/iiitkalyanifosc.github.io

**Comment by zeus0789** [comment]
Lets keep events.html your way and for projects.html have a look at my pr

**Comment by anubhavp28** [comment]
okay

**Comment by Satyam-TG** [comment]
@anubhavp28 your work is nice. Great in fact. But, the mobile layout seems to be broken in that.

**Comment by anubhavp28** [comment]
I know, I am working on it.

**Comment by anubhavp28** [comment]
@Satyam-TG @zeus0789 Now, the events page works well on mobile. Though I have to decrease the size of background banner image (probably in later PR).  I refactored CSS, now it is way cleaner.

**Comment by zeus0789** [comment]
@anubhavp28 yeah looks good now. I suggest you should merge the prs so that we can complete this website. Also I have completed changes on the index.html which I would like to show.

**Pull request merged**
